logging:
  level:
    root: warn
    org:
      flywaydb: debug
      springframework:
        web:
          client: trace
db:
  jdbc-url: dbc:mysql://localhost:3306/flywaydb?allowMultiQueries=true&serverTimezone=GMT%2B8
  jdbc-user: root
  repo-username: admin
  repo-password: Aa123456.
project:

