services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: artifactory
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "artifactory"]
      interval: 5s
      timeout: 3s
      retries: 5

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.5
    environment:
      EXTRA_JAVA_OPTIONS: "-Xms512m -Xmx2g"
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./artifactory_data/artifactory:/var/opt/jfrog/artifactory
      - ./config/system.yaml:/var/opt/jfrog/artifactory/etc/system.yaml
      - ./config/master.key:/var/opt/jfrog/artifactory/etc/security/master.key
    depends_on:
      postgres:
        condition: service_healthy
  db:
    container_name: flyway_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "flywaydb"
      MYSQL_USER: "flyway"
      MYSQL_PASSWORD: "flyway"
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
